import { existsSync, mkdirSync } from 'fs';
import path from 'path';

import { getGhShimHostBinDir } from './gh-shim-script';
import {
  normalizeComparablePath,
  toSingleQuotedShellString,
  writeIfChanged,
} from './shell-file-utils';

const buildInheritedSourceTarget = (
  filename: '.zshenv' | '.zprofile' | '.zshrc' | '.zlogin' | '.zlogout',
  inheritZdotdir: string | undefined,
  currentZdotdirPath: string
): string => {
  if (!inheritZdotdir) {
    return `$HOME/${filename}`;
  }

  if (normalizeComparablePath(inheritZdotdir) === normalizeComparablePath(currentZdotdirPath)) {
    return `$HOME/${filename}`;
  }

  return toSingleQuotedShellString(path.join(inheritZdotdir, filename));
};

const buildZshPassthroughSource = (
  filename: '.zshenv' | '.zprofile' | '.zshrc' | '.zlogin' | '.zlogout',
  inheritZdotdir: string | undefined,
  currentZdotdirPath: string
): string => {
  const inheritedTarget = buildInheritedSourceTarget(filename, inheritZdotdir, currentZdotdirPath);
  return `# Auto-generated by Lody for gh wrapper support.
if [ -f ${inheritedTarget} ]; then
  . ${inheritedTarget}
fi
`;
};

export const shouldInjectZdotdirForGhShim = (): boolean =>
  process.platform === 'darwin' && (existsSync('/bin/zsh') || existsSync('/usr/bin/zsh'));

export const ensureLodyZdotdirForGhShim = (
  inheritZdotdir?: string,
  brokerStateFilePath?: string
): string => {
  const zdotdirPath = path.join(getGhShimHostBinDir(brokerStateFilePath), 'zdotdir');
  mkdirSync(zdotdirPath, { recursive: true });

  for (const filename of ['.zshenv', '.zprofile', '.zshrc', '.zlogin', '.zlogout'] as const) {
    const source = buildZshPassthroughSource(filename, inheritZdotdir, zdotdirPath);
    const restorePath =
      filename === '.zprofile'
        ? `\nexport PATH=${toSingleQuotedShellString(getGhShimHostBinDir(brokerStateFilePath))}:"$PATH"\n`
        : '';
    writeIfChanged(path.join(zdotdirPath, filename), source + restorePath);
  }

  return zdotdirPath;
};
