import { mkdirSync } from 'fs';
import path from 'path';
import { getLodyDataDir } from '@lody/shared/node/installation-profile';

import { GITHUB_CREDENTIAL_ENV_KEYS } from './gh-token-env';
import { getGhShimHostBinDir } from './gh-shim-script';
import { toSingleQuotedShellString, writeIfChanged } from './shell-file-utils';

/** Keep shell startup from restoring credentials scrubbed at the Session boundary. */
export const applyNonOwnerShellEnv = (
  env: NodeJS.ProcessEnv,
  brokerStateFilePath?: string
): void => {
  if (process.platform === 'win32') return;

  // These files never source owner dotfiles and never share a path with owner
  // wrappers. Concurrent sessions must not rewrite one another's startup policy.
  const shimBinDir = brokerStateFilePath ? getGhShimHostBinDir(brokerStateFilePath) : undefined;
  const startupDir = shimBinDir
    ? path.join(shimBinDir, 'non-owner-shell')
    : path.join(getLodyDataDir(), 'shell-env', 'non-owner');
  mkdirSync(startupDir, { recursive: true });
  const bashEnv = path.join(startupDir, 'bashenv');
  const source = `# Auto-generated by Lody for non-owner sessions.
unset ${GITHUB_CREDENTIAL_ENV_KEYS.join(' ')}
export BASH_ENV=${toSingleQuotedShellString(bashEnv)}
export ZDOTDIR=${toSingleQuotedShellString(startupDir)}
${shimBinDir ? `export PATH=${toSingleQuotedShellString(shimBinDir)}:"$PATH"\n` : ''}
`;
  // Restore the shim after system zsh profiles (e.g. macOS path_helper).
  // This controls our startup hooks, not native shells that ignore/replace them
  // (e.g. interactive bash); it is not OS-level credential isolation.
  for (const filename of ['bashenv', '.zshenv', '.zprofile', '.zshrc', '.zlogin', '.zlogout']) {
    writeIfChanged(path.join(startupDir, filename), source);
  }
  env.BASH_ENV = bashEnv;
  env.ZDOTDIR = startupDir;
};
