export const CODEX_API_KEY_ENV = 'CODEX_API_KEY';
export const CODEX_CONFIG_ENV = 'CODEX_CONFIG';
export const LODY_CODEX_MODEL_PROVIDER_ID = 'lody-custom-endpoint';

export type CodexAuthenticationMode = 'chatgpt' | 'api-key';

export type LodyCodexCustomProvider = {
  apiKey: string;
  baseUrl: string;
};

function asRecord(value: unknown): Record<string, unknown> | null {
  if (!value || typeof value !== 'object' || Array.isArray(value)) return null;
  return value as Record<string, unknown>;
}

function parseCodexConfig(value: string | undefined): Record<string, unknown> | null {
  if (!value?.trim()) return null;
  try {
    return asRecord(JSON.parse(value));
  } catch {
    return null;
  }
}

/**
 * Reads only the custom provider shape generated by Lody. Arbitrary user-authored
 * CODEX_CONFIG values remain advanced environment overrides and are never claimed
 * or rewritten by the dedicated credential form.
 */
export function getLodyCodexCustomProvider(
  env: Record<string, string | undefined> | undefined
): LodyCodexCustomProvider | null {
  const config = parseCodexConfig(env?.[CODEX_CONFIG_ENV]);
  if (config?.model_provider !== LODY_CODEX_MODEL_PROVIDER_ID) return null;
  const providers = asRecord(config.model_providers);
  const provider = asRecord(providers?.[LODY_CODEX_MODEL_PROVIDER_ID]);
  if (
    !provider ||
    typeof provider.base_url !== 'string' ||
    provider.env_key !== CODEX_API_KEY_ENV ||
    provider.requires_openai_auth !== false ||
    provider.wire_api !== 'responses'
  ) {
    return null;
  }
  return {
    apiKey: env?.[CODEX_API_KEY_ENV]?.trim() ?? '',
    baseUrl: provider.base_url,
  };
}

export function buildLodyCodexCustomProviderEnv(
  env: Record<string, string>,
  input: LodyCodexCustomProvider
): Record<string, string> {
  const next = { ...env };
  const config = parseCodexConfig(next[CODEX_CONFIG_ENV]) ?? {};
  const providers = { ...(asRecord(config.model_providers) ?? {}) };
  providers[LODY_CODEX_MODEL_PROVIDER_ID] = {
    name: 'Custom OpenAI-compatible endpoint',
    base_url: input.baseUrl.trim(),
    env_key: CODEX_API_KEY_ENV,
    wire_api: 'responses',
    requires_openai_auth: false,
  };
  next[CODEX_API_KEY_ENV] = input.apiKey.trim();
  next[CODEX_CONFIG_ENV] = JSON.stringify({
    ...config,
    model_provider: LODY_CODEX_MODEL_PROVIDER_ID,
    model_providers: providers,
  });
  return next;
}

export function removeLodyCodexCustomProviderEnv(
  env: Record<string, string>
): Record<string, string> {
  if (!getLodyCodexCustomProvider(env)) return { ...env };

  const next = { ...env };
  const config = parseCodexConfig(next[CODEX_CONFIG_ENV]) ?? {};
  const providers = { ...(asRecord(config.model_providers) ?? {}) };
  delete providers[LODY_CODEX_MODEL_PROVIDER_ID];
  delete config.model_provider;
  if (Object.keys(providers).length > 0) {
    config.model_providers = providers;
  } else {
    delete config.model_providers;
  }
  delete next[CODEX_API_KEY_ENV];
  if (Object.keys(config).length > 0) {
    next[CODEX_CONFIG_ENV] = JSON.stringify(config);
  } else {
    delete next[CODEX_CONFIG_ENV];
  }
  return next;
}
